<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [19]:
# importing numpy
import numpy as np

In [21]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array1 = np.array([1, 2, 3, 4, 5, 0])
print(array1)
print(array1.all())

[1 2 3 4 5 0]
False


In [23]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array2 = np.array([3, -1, 3, 7, 2])
print(array2)
print(array2.any())

[ 3 -1  3  7  2]
True


In [25]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array3 = np.zeros(4, dtype=int)
print(array3)
print(array3.any())

[0 0 0 0]
False


In [33]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array4 = np.array([56, -2, 7])
print(array4)
print(array4.itemsize * array4.size)

[56 -2  7]
12


In [45]:
# Create a numpy array with 10 zeros and print the array.
array5 = np.zeros(10, dtype=int)
print(array5)
# Create a numpy array with 6 ones and print the array.
array6 = np.ones(6, dtype=int)
print(array6)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
array7 = 3 * np.ones(12, dtype=int)
print(array7)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [49]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array8 = np.arange(8, 21)
print(array8)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
array9 = np.arange(8, 21, 2)
print(array9)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [63]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
rarray1 = np.random.normal(2, 0.5, 100)
print("First array")
print(rarray1.mean())
print(rarray1.max())
print(rarray1.min())
print(rarray1.std())
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
rarray2 = np.random.normal(2, 0.5, 1000)
print("Second array")
print(rarray2.mean())
print(rarray2.max())
print(rarray2.min())
print(rarray2.std())
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
rarray3 = np.random.normal(2, 0.5, 1000000)
print("Third array")
print(rarray3.mean())
print(rarray3.max())
print(rarray3.min())
print(rarray3.std())
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
print("The more elements, the more the mean and std of the random array approaches the theoretically 'perfect' intended values")

First array
1.9512099249363792
3.283382642268638
0.5942551648784109
0.5374627059795839
Second array
2.0034009276965734
3.3941756646155703
0.6048957175586294
0.5130634196138566
Third array
2.000020673338195
4.66937242971758
-0.3911789430358805
0.4995480918052856
The more elements, the more the mean and std of the random array approaches the theoretically 'perfect' intended values
