<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [11]:
matrix_a = np.array([[5, 2, 3], [6, 1, 3], [2, 4, 1]])
matrix_b = matrix_a[:2,:2]
matrix_c = matrix_a[1:,1:]
print(matrix_a)
print(matrix_b)
print(matrix_c)

[[5 2 3]
 [6 1 3]
 [2 4 1]]
[[5 2]
 [6 1]]
[[1 3]
 [4 1]]


In [15]:
matrix_d = np.array([[4, -7, 4], [5, 6, -1], [-4, 2, 5]])
print(matrix_d)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  1  5]]


In [29]:
print("AD:")
print(np.matmul(matrix_a, matrix_d))
print("DA:")
print(np.matmul(matrix_d, matrix_a))
print("Are they equal? ", np.array_equal(np.matmul(matrix_a, matrix_d), np.matmul(matrix_d, matrix_a)))

AD:
[[ 18 -20  33]
 [ 17 -33  38]
 [ 24  11   9]]
DA:
[[-14  17  -5]
 [ 59  12  32]
 [ -4  13  -4]]
Are they equal?  False


In [55]:
print("|B| is:")
print((5 * 1) - (6 * 2))
print("B^-1 is:")
# calculated in excel, slowly
b_inv = np.array([[-1, 2], [6, -5]]) / 7
print(b_inv)
print("According to numpy:")
print("|B| is:")
print(np.linalg.det(matrix_b))
print("B^-1 is:")
print(np.linalg.inv(matrix_b))

print("These calculations agree")

|B| is:
-7
B^-1 is:
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
According to numpy:
|B| is:
-6.999999999999998
B^-1 is:
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
These calculations agree


In [63]:
d_inv = np.linalg.inv(matrix_d)
print(np.matmul(matrix_d, d_inv))
print(np.matmul(d_inv, matrix_d))
print("These are similar to identity matrices but due to floating point error the zero values are slightly non-zero")

[[ 1.00000000e+00  5.55111512e-17  1.11022302e-16]
 [-5.55111512e-17  1.00000000e+00 -2.77555756e-17]
 [ 5.55111512e-17 -1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  2.35922393e-16  1.38777878e-17]
 [ 2.77555756e-17  1.00000000e+00 -3.46944695e-17]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]
These are similar to identity matrices but due to floating point error the zero values are slightly non-zero
